name: sleap-roots

channels:
  - conda-forge
  - defaults

dependencies:
  - python=3.11
  - numpy
  - matplotlib
  - seaborn
  - pandas
  - shapely
  - attrs
  - scikit-image
  - jupyterlab
  - pip
  - pip:
    - "--editable=.[dev]"